#!/bin/bash
set -e

mysql -u root -p"${MYSQL_ROOT_PASSWORD}" <<-EOSQL
    CREATE DATABASE IF NOT EXISTS 
    CREATE DATABASE IF NOT EXISTS 
    GRANT ALL PRIVILEGES ON 
    GRANT ALL PRIVILEGES ON 
    FLUSH PRIVILEGES;
EOSQL
