global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Traefik metrics
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']
    metrics_path: /metrics

  # MySQL metrics
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql-exporter:9104']

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Elasticsearch metrics
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch-exporter:9114']

  # Node exporter (if added)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # WordPress application metrics (custom)
  - job_name: 'wordpress'
    static_configs:
      - targets: ['wordpress1:9090', 'wordpress2:9090']
    metrics_path: /wp-admin/admin-ajax.php
    params:
      action: ['wp_metrics']
    scrape_interval: 30s