groups:
  - name: wordpress.rules
    rules:
      # WordPress Response Time
      - alert: WordPressHighResponseTime
        expr: avg_over_time(traefik_service_request_duration_seconds{service=~"wordpress.*"}[5m]) > 2
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "WordPress site {{ $labels.service }} has high response time"
          description: "WordPress site {{ $labels.service }} response time is {{ $value }}s"

      # WordPress Error Rate
      - alert: WordPressHighErrorRate
        expr: rate(traefik_service_requests_total{service=~"wordpress.*",code=~"5.."}[5m]) > 0.1
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "WordPress site {{ $labels.service }} has high error rate"
          description: "WordPress site {{ $labels.service }} error rate is {{ $value }}"

      # MySQL Connection Issues
      - alert: MySQLDown
        expr: mysql_up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "MySQL is down"
          description: "MySQL database is not responding"

      # Redis Connection Issues
      - alert: RedisDown
        expr: redis_up == 0
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Redis is down"
          description: "Redis cache server is not responding"

      # High Memory Usage
      - alert: HighMemoryUsage
        expr: (container_memory_usage_bytes / container_spec_memory_limit_bytes) * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Container {{ $labels.name }} has high memory usage"
          description: "Container {{ $labels.name }} memory usage is {{ $value }}%"

      # High CPU Usage
      - alert: HighCPUUsage
        expr: rate(container_cpu_usage_seconds_total[5m]) * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Container {{ $labels.name }} has high CPU usage"
          description: "Container {{ $labels.name }} CPU usage is {{ $value }}%"