global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: INFO

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: wp-dev-platform_wp-network
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

# Self-signed certificates for development
tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/ssl/certs/dev-cert.pem
        keyFile: /etc/ssl/certs/dev-key.pem

# Metrics for Prometheus
metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    addRoutersLabels: true