#!/bin/bash
set -euo pipefail

# Apache + PHP-FPM entrypoint for the matrix apache stack (Ubuntu 24.04 base).
# Replaces the official wordpress:*-fpm docker-entrypoint.sh, which is no longer
# present after the Ubuntu rebase. Responsibilities:
#   1. Generate wp-config.php on first boot from WORDPRESS_DB_* env vars + salts.
#   2. Ensure the FPM runtime socket dir exists.
#   3. Start php-fpm in the background, then Apache in the foreground.

PHP_VERSION="${PHP_VERSION:-8.3}"
DOCROOT="${WORDPRESS_DOCROOT:-/var/www/html}"
WP_CONFIG="$DOCROOT/wp-config.php"

salt() {
    # 64 chars of URL-safe randomness, derived locally (no network dependency).
    head -c 48 /dev/urandom | base64 | tr '+/' '-_' | tr -d '\n=' | cut -c1-64
}

write_wp_config() {
    [[ -f "$WP_CONFIG" ]] && return 0
    [[ -f "$DOCROOT/wp-config-sample.php" ]] || return 0

    local db_name db_user db_pass db_host debug
    db_name="${WORDPRESS_DB_NAME:-wordpress}"
    db_user="${WORDPRESS_DB_USER:-wp_user}"
    db_pass="${WORDPRESS_DB_PASSWORD:-wp_password}"
    db_host="${WORDPRESS_DB_HOST:-db:3306}"
    debug="$(printf '%s' "${WORDPRESS_DEBUG:-false}" | tr '[:upper:]' '[:lower:]')"
    case "$debug" in
        true|1|yes|on) debug="true" ;;
        *) debug="false" ;;
    esac

    cat > "$WP_CONFIG" <<PHP
<?php
/**
 * Generated by matrix apache-fpm entrypoint (replaces the official WP entrypoint).
 */
define( 'DB_NAME',     '$db_name' );
define( 'DB_USER',     '$db_user' );
define( 'DB_PASSWORD', '$db_pass' );
define( 'DB_HOST',     '$db_host' );
define( 'DB_CHARSET',  'utf8mb4' );
define( 'DB_COLLATE',  '' );

define( 'AUTH_KEY',         '$(salt)' );
define( 'SECURE_AUTH_KEY',  '$(salt)' );
define( 'LOGGED_IN_KEY',    '$(salt)' );
define( 'NONCE_KEY',        '$(salt)' );
define( 'AUTH_SALT',        '$(salt)' );
define( 'SECURE_AUTH_SALT', '$(salt)' );
define( 'LOGGED_IN_SALT',   '$(salt)' );
define( 'NONCE_SALT',       '$(salt)' );

\$table_prefix = 'wp_';

define( 'WP_DEBUG', $debug );
define( 'WP_DEBUG_LOG', $debug );
define( 'WP_DEBUG_DISPLAY', false );

if ( ! defined( 'ABSPATH' ) ) {
    define( 'ABSPATH', __DIR__ . '/' );
}

require_once ABSPATH . 'wp-settings.php';
PHP

    chown www-data:www-data "$WP_CONFIG" 2>/dev/null || true
    chmod 660 "$WP_CONFIG" 2>/dev/null || true
}

write_wp_config

# Ensure the FPM runtime socket directory exists and is owned by www-data.
mkdir -p /run/php
chown www-data:www-data /run/php 2>/dev/null || true

# Start PHP-FPM (background), then Apache (foreground).
php-fpm"$PHP_VERSION" -D || php-fpm -D

exec /usr/sbin/apache2ctl -D FOREGROUND
